logback:
  amqp:
    exchange: core-valid-task-manager-logs-exchange
    routing-key: "#"
spring:
  banner:
    location: classpath:banner.txt
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:gridcapa}
    password: ${RABBITMQ_PASSWORD:gridcapa}
    template:
      reply-timeout: 6000000
  cloud:
    stream:
      function:
        definition: interrupt;request
      default:
        binder: rabbit
      bindings:
        interrupt-in-0:
          destination: core-valid-stop-task
        request-in-0:
          destination: core-valid-request
        request-out-0:
          destination: core-valid-response
        task-status-update:
          destination: core-valid-task-status-updated

rao-runner-server:
  amqp:
    client-app-id: core-valid-runner
    queue-name: rao-request-queue

core-valid-runner:
  async-time-out: 600000 # 10min (10*60*1000)
  whitelist:
    - http://localhost:9000
    - http://minio:9000
    - file:/
  search-tree-rao-parameters:
    max-curative-topo-per-tso:
      FR: 1
    max-curative-pst-per-tso:
      FR: 0
    max-curative-ra-per-tso:
      FR: 1

minio-adapter:
  bucket: gridcapa
  base-path: CORE/VALID
  access-key: gridcapa
  secret-key: gridcapa
  url: http://localhost:9000/