spring:
  banner:
    location: classpath:banner.txt
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    template:
      reply-timeout: 6000000

rao-runner-server:
  amqp:
    queue-name: ${RAO_ADAPTER_SERVER_QUEUE_NAME:rao-request-queue}

core-valid-server:
  requests:
    queue-name: ${CORE_VALID_SERVER_QUEUE_NAME:core-valid-requests}
  responses:
    exchange: core-valid-response
    expiration: 60000
  minio:
    access:
      name: ${MINIO_USERNAME:minioadmin}
      secret: ${MINIO_PASSWORD:minioadmin}
    url: http://${MINIO_HOST:localhost}:${MINIO_PORT:9000}
    bucket: ${MINIO_BUCKET:gridcapa}
    base-path: ${CORE_VALID_SERVER_MINIO_BASE_PATH:CORE/VALID/}
  security:
    whitelist:
      - http://${MINIO_HOST:localhost}:${MINIO_PORT:9000}
      - file:/
      - http://minio:9000/

server:
  port: ${CORE_VALID_SERVER_PORT:8080}