spring:
  banner:
    location: classpath:banner.txt
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    template:
      reply-timeout: 6000000
  cloud:
    stream:
      bindings:
        task-status-update:
          binder: rabbit
          destination: task-status-updated

core-valid-server:
  bindings:
    request:
      destination: core-valid-request
      routing-key: "#"
      group: cse-idcc-runner
    response:
      destination: cse-response
      expiration: 60000
  requests:
    queue-name: ${CORE_VALID_SERVER_QUEUE_NAME:core-valid-requests}
  responses:
    exchange: core-valid-response
    expiration: 60000
  minio:
    access:
      name: ${MINIO_USERNAME:minioadmin}
      secret: ${MINIO_PASSWORD:minioadmin}
    url: http://${MINIO_HOST:localhost}:${MINIO_PORT:9000}
    bucket: ${MINIO_BUCKET:core-valid-data}
    base-path: ${CORE_VALID_SERVER_MINIO_BASE_PATH:core-valid/}
  security:
    whitelist:
      - http://${MINIO_HOST:localhost}:${MINIO_PORT:9000}

server:
  port: ${CORE_VALID_SERVER_PORT:8080}

core-valid-runner:
  xnodes:
    file-path: /home/farao/xnodes/xnodes.xml
  bindings:
    request:
      destination: core-valid-request
      routing-key: "#"
      group: core-valid-runner
    response:
      destination: core-valid-response
      expiration: 60000
  whitelist:
    - http://minio:9000/