spring:
  banner:
    location: classpath:banner.txt
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    template:
      reply-timeout: 6000000
  cloud:
    stream:
      bindings:
        task-status-update:
          binder: rabbit
          destination: task-status-updated

core-valid-runner:
  bindings:
    request:
      destination: core-valid-requests
      routing-key: "#"
    response:
      destination: core-valid-response
      expiration: 600000
  whitelist:
    - http://${MINIO_HOST:localhost}:${MINIO_PORT:9000}

minio:
  access:
    name: ${MINIO_USERNAME:minioadmin}
    secret: ${MINIO_PASSWORD:minioadmin}
  url: http://${MINIO_HOST:localhost}:${MINIO_PORT:9000}
  bucket: ${MINIO_BUCKET:core-valid-data}
  base-path: ${CORE_VALID_SERVER_MINIO_BASE_PATH:core-valid/}

server:
  port: ${CORE_VALID_SERVER_PORT:8080}