logback:
  amqp:
    exchange: task-manager-logs-exchange
    routing-key: "#"
spring:
  banner:
    location: classpath:banner.txt
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:gridcapa}
    password: ${RABBITMQ_PASSWORD:gridcapa}
    template:
      reply-timeout: 6000000
  cloud:
    stream:
      bindings:
        task-status-update:
          binder: rabbit
          destination: task-status-updated

rao-runner-server:
  amqp:
    queue-name: ${RAO_ADAPTER_SERVER_QUEUE_NAME:rao-request-queue}

core-valid-runner:
  async-time-out: 600000 # 10min (10*60*1000)
  bindings:
    request:
      destination: core-valid-requests
      routing-key: "#"
    response:
      destination: core-valid-response
      expiration: 600000
  whitelist:
    - http://localhost:9000
    - http://minio:9000
    - file:/

minio-adapter:
  bucket: gridcapa
  base-path: CORE/VALID
  access-key: gridcapa
  secret-key: gridcapa
  url: http://localhost:9000/